title: "'Ilm"
description: Notes on Ê¿ilm (knowledge) from Islamic sources and personal learning.
theme: just-the-docs

url: https://ekxk.github.io/ilm

aux_links:
  Template Repository: https://github.com/ekxk/ilm
